#ifndef _MODULES_HH
#define _MODULES_HH
#define MODULE_AUDIO_WAV_SYSTEM 
#define MODULE_CART 
#define MODULE_FLF_CORE 
#define MODULE_LATTICE_BASIC 
#define MODULE_LATTICE_DT 
#define MODULE_LM_ARPA 
#define MODULE_LM_ZEROGRAM 
#define MODULE_MM_DT 
#define MODULE_MM_BATCH 
#define MODULE_SPEECH_DT 
#define MODULE_SPEECH_ALIGNMENT_FLOW_NODES 
#define MODULE_SPEECH_LATTICE_FLOW_NODES 
#define MODULE_SPEECH_LATTICE_ALIGNMENT 
#endif
